/// <reference lib="webworker" />

// Service Worker com suporte a Web Push Notifications
// Este arquivo é usado pelo VitePWA injectManifest

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: ServiceWorkerGlobalScope;

// Extended notification options for service worker
interface ExtendedNotificationOptions extends NotificationOptions {
  actions?: { action: string; title: string; icon?: string }[];
  vibrate?: number[];
  renotify?: boolean;
}

// Claim clients immediately
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cleanup old caches
cleanupOutdatedCaches();

// Cache Google Fonts
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365 // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200]
      })
    ]
  })
);

registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: 'gstatic-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200]
      })
    ]
  })
);

// Cache images
registerRoute(
  /\.(?:png|jpg|jpeg|svg|gif|webp)$/,
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30 // 30 days
      })
    ]
  })
);

// Network first for Supabase API
registerRoute(
  /^https:\/\/.*\.supabase\.co\/.*/i,
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 10,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 5 // 5 minutes
      })
    ]
  })
);

// ============================================
// WEB PUSH NOTIFICATION HANDLERS
// ============================================

interface NotificationPayload {
  title?: string;
  body?: string;
  icon?: string;
  badge?: string;
  tag?: string;
  data?: { url?: string; [key: string]: unknown };
  requireInteraction?: boolean;
  actions?: { action: string; title: string }[];
  vibrate?: number[];
  renotify?: boolean;
}

/**
 * Handle push events - triggered when server sends a push notification
 * This runs even when the app is closed or in background
 */
self.addEventListener('push', (event: PushEvent) => {
  console.log('[SW] Push event received:', event);

  const defaultData: NotificationPayload = {
    title: 'Food Comanda Pro',
    body: 'Você tem uma nova notificação',
    icon: '/pwa-icon-192.png',
    badge: '/pwa-icon-192.png',
    tag: 'default',
    data: { url: '/admin' }
  };

  let notificationData: NotificationPayload = { ...defaultData };

  // Try to parse the push data
  if (event.data) {
    try {
      const payload = event.data.json() as NotificationPayload;
      notificationData = {
        title: payload.title || defaultData.title,
        body: payload.body || defaultData.body,
        icon: payload.icon || defaultData.icon,
        badge: payload.badge || defaultData.badge,
        tag: payload.tag || defaultData.tag,
        data: payload.data || defaultData.data,
        requireInteraction: payload.requireInteraction ?? true,
        actions: payload.actions || [
          { action: 'open', title: 'Abrir' },
          { action: 'dismiss', title: 'Dispensar' }
        ],
        vibrate: [200, 100, 200],
        renotify: true
      };
    } catch (e) {
      console.error('[SW] Error parsing push data:', e);
      notificationData.body = event.data.text();
    }
  }

  console.log('[SW] Showing notification:', notificationData.title);

  // Use type assertion for extended notification options
  const options: ExtendedNotificationOptions = {
    body: notificationData.body,
    icon: notificationData.icon,
    badge: notificationData.badge,
    tag: notificationData.tag,
    data: notificationData.data,
    requireInteraction: notificationData.requireInteraction,
    actions: notificationData.actions,
    vibrate: notificationData.vibrate,
    renotify: notificationData.renotify
  };

  const promiseChain = self.registration.showNotification(
    notificationData.title!,
    options as NotificationOptions
  );

  event.waitUntil(promiseChain);
});

/**
 * Handle notification click - user clicked on the notification
 */
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  console.log('[SW] Notification click:', event.action);

  event.notification.close();

  // Handle dismiss action
  if (event.action === 'dismiss') {
    return;
  }

  // Get the URL to open
  const urlToOpen = (event.notification.data as { url?: string })?.url || '/admin';
  const fullUrl = new URL(urlToOpen, self.location.origin).href;

  console.log('[SW] Opening URL:', fullUrl);

  // Try to focus existing window or open new one
  const promiseChain = self.clients.matchAll({
    type: 'window',
    includeUncontrolled: true
  }).then((windowClients) => {
    // Check if there's already a window/tab open with this URL
    for (const client of windowClients) {
      if (client.url === fullUrl && 'focus' in client) {
        return client.focus();
      }
    }
    
    // Check if there's any window we can navigate
    for (const client of windowClients) {
      if ('navigate' in client && 'focus' in client) {
        return (client as WindowClient).navigate(fullUrl).then(() => client.focus());
      }
    }
    
    // No existing window, open a new one
    if (self.clients.openWindow) {
      return self.clients.openWindow(fullUrl);
    }
  });

  event.waitUntil(promiseChain);
});

/**
 * Handle notification close - user dismissed the notification
 */
self.addEventListener('notificationclose', (event: NotificationEvent) => {
  console.log('[SW] Notification closed:', event.notification.tag);
  // Can be used for analytics
});

/**
 * Handle push subscription change - subscription was invalidated
 */
self.addEventListener('pushsubscriptionchange', (event: Event) => {
  console.log('[SW] Push subscription changed');
  
  // The subscription was invalidated, we need to resubscribe
  // This is handled by the main app when it loads
  // We can post a message to any open windows
  const promiseChain = self.clients.matchAll({
    type: 'window',
    includeUncontrolled: true
  }).then((windowClients) => {
    for (const client of windowClients) {
      client.postMessage({
        type: 'PUSH_SUBSCRIPTION_CHANGED',
        message: 'Push subscription needs to be renewed'
      });
    }
  });

  (event as ExtendableEvent).waitUntil(promiseChain);
});

console.log('[SW] Service Worker with Push support loaded');
